### ISSUE TITLE
Major Privacy is not activated - driver protections disabled! Not sure why I'm getting this message.

### ISSUE THREAD

**Issue by futuremotiondev** [xanasoft/MajorPrivacy#16]
Just extracted Major Privacy and every time I run it I get this:

![MajorPrivacy_kLEPfMBeno](https://github.com/user-attachments/assets/00974822-3089-4177-8f4f-cfba6c2a456c)

How do I activate it?

The settings screen to enter my certificate info isn't intractable - I can't paste my certificate info.

![MajorPrivacy_1O0S0Zvyls](https://github.com/user-attachments/assets/ff75e7c1-4277-4e88-a63d-e44d119e5f2f)

**Comment by DavidXanatos** [comment]
I think the connection with the driver may be failed, in that case it wil also see itself as not activated.

**Comment by DavidXanatos** [comment]
0.96.1 is out please try it
