### ISSUE TITLE
Mount the encrypted volume in chunks

### ISSUE THREAD

**Issue by Proposer233** [xanasoft/MajorPrivacy#29]
To make it more difficult for malicious programs to directly read files in mounted encrypted volumes in physical memory, I recommend employing the techniques shown in the title.
After you enable this technology, when you mount an encrypted volume, the key is encrypted and stored in a trusted memory region (such as TPM), and the data is not directly loaded into memory.
Different files of the volume are encrypted in chunks, and different encryption blocks use different keys, but they can all be deduced from the master key. When an application attempts to read a file in it, it temporarily mounts the block in which the file resides, and unmounts the block as soon as the file is no longer in use, at same time clearing the subkey of the block.

**Comment by DavidXanatos** [comment]
we don't use TPM as its slow and useless, ity only good to hold master keys or do asymetric crypto for authentication.
If the performance is not to suck teh crypto for the blocks must be done by the driver using the CPU's AES builtin instructions, the data on disk are encrypted/decrypted on the fly we dont hold a copy of the entire disk in memory anyware, there wouldnt be enough RAM for that anywayson most systems.
