### ISSUE TITLE
The idea of deep startup based on the system bootstrap record

### ISSUE THREAD

**Issue by Proposer233** [xanasoft/MajorPrivacy#33]
Theoretically, we could register an option in the Windows Startup Manager, such as "MajorPrivacy-Personalize Windows 
 10 Professional". When the user selects this option, our module is launched first, and then the initial boot phase of the Windows system is proceeded to.

**Comment by DavidXanatos** [comment]
I don't see real utility in that, also MSFT will most likely not like it.
We need them to like us to sign the driver.
