### ISSUE TITLE
Program locks up when selecting CEIP group to be disabled

### ISSUE THREAD

**Issue by ex0a** [xanasoft/MajorPrivacy#4]
While disabling some telemetry, the entire application froze when I selected the group for CEIP. When reopening the application, it freezes again when I attempt to go back to the telemetry area.

![MajorPrivacy_telemetry_crash](https://github.com/xanasoft/MajorPrivacy/assets/441857/a7fec07b-e02f-4efc-be19-6b44a48deb71)

**Comment by DavidXanatos** [comment]
will be fixed in the soon to be released 0.95.0
